# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c2eebf8a664b66724f9d7cd4250978ed106cd8d48fb60c95d24fe89edf781b546a479f31b380d48df28f8ae676c4e92591671cddbb4804dccad7d7eb5f70be7

test:
  secret_key_base: 65e8b2af2192bd2e29d6aa8c536a01bf8c4eabff3439d1479a26f275931565bb37fcdfc8fe5ce9b3f0d9e2ad2fe57a15607d2137133a1ec0e1b73e95342d1cf1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
